version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: dnd-postgres
    restart: always
    environment:
      POSTGRES_USER: dnd_user
      POSTGRES_PASSWORD: dnd_password
      POSTGRES_DB: dndgames
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
